[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/config